name: Python Build and Test

on:
  push:
    branches:
      - master  # Customize this to your main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify your desired Python version

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt  # Adjust this based on your project setup

    - name: Install distutils
      run: python -m ensurepip && python -m pip install distutils

    - name: Run tests
      run: |
        python -m unittest discover -s djangoapp/  # Replace with your test command
